// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sudoku.proto

#include "sudoku.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace sudoku {
class SudokuRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SudokuRequest> _instance;
} _SudokuRequest_default_instance_;
class SudokuResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SudokuResponse> _instance;
} _SudokuResponse_default_instance_;
}  // namespace sudoku
static void InitDefaultsSudokuRequest_sudoku_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sudoku::_SudokuRequest_default_instance_;
    new (ptr) ::sudoku::SudokuRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sudoku::SudokuRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SudokuRequest_sudoku_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSudokuRequest_sudoku_2eproto}, {}};

static void InitDefaultsSudokuResponse_sudoku_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sudoku::_SudokuResponse_default_instance_;
    new (ptr) ::sudoku::SudokuResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sudoku::SudokuResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SudokuResponse_sudoku_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSudokuResponse_sudoku_2eproto}, {}};

void InitDefaults_sudoku_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_SudokuRequest_sudoku_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SudokuResponse_sudoku_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_sudoku_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_sudoku_2eproto = nullptr;
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors_sudoku_2eproto[1];

const ::google::protobuf::uint32 TableStruct_sudoku_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuRequest, checkerboard_),
  0,
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuResponse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuResponse, solved_),
  PROTOBUF_FIELD_OFFSET(::sudoku::SudokuResponse, checkerboard_),
  1,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::sudoku::SudokuRequest)},
  { 7, 14, sizeof(::sudoku::SudokuResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sudoku::_SudokuRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sudoku::_SudokuResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_sudoku_2eproto = {
  {}, AddDescriptors_sudoku_2eproto, "sudoku.proto", schemas,
  file_default_instances, TableStruct_sudoku_2eproto::offsets,
  file_level_metadata_sudoku_2eproto, 2, file_level_enum_descriptors_sudoku_2eproto, file_level_service_descriptors_sudoku_2eproto,
};

const char descriptor_table_protodef_sudoku_2eproto[] =
  "\n\014sudoku.proto\022\006sudoku\"%\n\rSudokuRequest\022"
  "\024\n\014checkerboard\030\001 \002(\t\"=\n\016SudokuResponse\022"
  "\025\n\006solved\030\001 \001(\010:\005false\022\024\n\014checkerboard\030\002"
  " \001(\t2G\n\rSudokuService\0226\n\005Solve\022\025.sudoku."
  "SudokuRequest\032\026.sudoku.SudokuResponseB\t\200"
  "\001\001\210\001\001\220\001\001"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_sudoku_2eproto = {
  false, InitDefaults_sudoku_2eproto, 
  descriptor_table_protodef_sudoku_2eproto,
  "sudoku.proto", &assign_descriptors_table_sudoku_2eproto, 208,
};

void AddDescriptors_sudoku_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_sudoku_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_sudoku_2eproto = []() { AddDescriptors_sudoku_2eproto(); return true; }();
namespace sudoku {

// ===================================================================

void SudokuRequest::InitAsDefaultInstance() {
}
class SudokuRequest::HasBitSetters {
 public:
  static void set_has_checkerboard(SudokuRequest* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SudokuRequest::kCheckerboardFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SudokuRequest::SudokuRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sudoku.SudokuRequest)
}
SudokuRequest::SudokuRequest(const SudokuRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_checkerboard()) {
    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
  // @@protoc_insertion_point(copy_constructor:sudoku.SudokuRequest)
}

void SudokuRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_SudokuRequest_sudoku_2eproto.base);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SudokuRequest::~SudokuRequest() {
  // @@protoc_insertion_point(destructor:sudoku.SudokuRequest)
  SharedDtor();
}

void SudokuRequest::SharedDtor() {
  checkerboard_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SudokuRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SudokuRequest& SudokuRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SudokuRequest_sudoku_2eproto.base);
  return *internal_default_instance();
}


void SudokuRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    checkerboard_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SudokuRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SudokuRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // required string checkerboard = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("sudoku.SudokuRequest.checkerboard");
        object = msg->mutable_checkerboard();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SudokuRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sudoku.SudokuRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string checkerboard = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checkerboard()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sudoku.SudokuRequest.checkerboard");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sudoku.SudokuRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sudoku.SudokuRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SudokuRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string checkerboard = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sudoku.SudokuRequest.checkerboard");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->checkerboard(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sudoku.SudokuRequest)
}

::google::protobuf::uint8* SudokuRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sudoku.SudokuRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string checkerboard = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sudoku.SudokuRequest.checkerboard");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->checkerboard(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sudoku.SudokuRequest)
  return target;
}

size_t SudokuRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sudoku.SudokuRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string checkerboard = 1;
  if (has_checkerboard()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->checkerboard());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SudokuRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sudoku.SudokuRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SudokuRequest* source =
      ::google::protobuf::DynamicCastToGenerated<SudokuRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sudoku.SudokuRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sudoku.SudokuRequest)
    MergeFrom(*source);
  }
}

void SudokuRequest::MergeFrom(const SudokuRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sudoku.SudokuRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_checkerboard()) {
    _has_bits_[0] |= 0x00000001u;
    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
}

void SudokuRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sudoku.SudokuRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SudokuRequest::CopyFrom(const SudokuRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sudoku.SudokuRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SudokuRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void SudokuRequest::Swap(SudokuRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SudokuRequest::InternalSwap(SudokuRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  checkerboard_.Swap(&other->checkerboard_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata SudokuRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_sudoku_2eproto);
  return ::file_level_metadata_sudoku_2eproto[kIndexInFileMessages];
}


// ===================================================================

void SudokuResponse::InitAsDefaultInstance() {
}
class SudokuResponse::HasBitSetters {
 public:
  static void set_has_solved(SudokuResponse* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_checkerboard(SudokuResponse* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SudokuResponse::kSolvedFieldNumber;
const int SudokuResponse::kCheckerboardFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SudokuResponse::SudokuResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sudoku.SudokuResponse)
}
SudokuResponse::SudokuResponse(const SudokuResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_checkerboard()) {
    checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
  }
  solved_ = from.solved_;
  // @@protoc_insertion_point(copy_constructor:sudoku.SudokuResponse)
}

void SudokuResponse::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_SudokuResponse_sudoku_2eproto.base);
  checkerboard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  solved_ = false;
}

SudokuResponse::~SudokuResponse() {
  // @@protoc_insertion_point(destructor:sudoku.SudokuResponse)
  SharedDtor();
}

void SudokuResponse::SharedDtor() {
  checkerboard_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SudokuResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SudokuResponse& SudokuResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SudokuResponse_sudoku_2eproto.base);
  return *internal_default_instance();
}


void SudokuResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    checkerboard_.ClearNonDefaultToEmptyNoArena();
  }
  solved_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SudokuResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SudokuResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional bool solved = 1 [default = false];
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_solved(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional string checkerboard = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("sudoku.SudokuResponse.checkerboard");
        object = msg->mutable_checkerboard();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SudokuResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sudoku.SudokuResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool solved = 1 [default = false];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_solved(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &solved_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string checkerboard = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checkerboard()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sudoku.SudokuResponse.checkerboard");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sudoku.SudokuResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sudoku.SudokuResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SudokuResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool solved = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->solved(), output);
  }

  // optional string checkerboard = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sudoku.SudokuResponse.checkerboard");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->checkerboard(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sudoku.SudokuResponse)
}

::google::protobuf::uint8* SudokuResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sudoku.SudokuResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool solved = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->solved(), target);
  }

  // optional string checkerboard = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->checkerboard().data(), static_cast<int>(this->checkerboard().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sudoku.SudokuResponse.checkerboard");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->checkerboard(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sudoku.SudokuResponse)
  return target;
}

size_t SudokuResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sudoku.SudokuResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string checkerboard = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->checkerboard());
    }

    // optional bool solved = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SudokuResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sudoku.SudokuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const SudokuResponse* source =
      ::google::protobuf::DynamicCastToGenerated<SudokuResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sudoku.SudokuResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sudoku.SudokuResponse)
    MergeFrom(*source);
  }
}

void SudokuResponse::MergeFrom(const SudokuResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sudoku.SudokuResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      checkerboard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.checkerboard_);
    }
    if (cached_has_bits & 0x00000002u) {
      solved_ = from.solved_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SudokuResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sudoku.SudokuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SudokuResponse::CopyFrom(const SudokuResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sudoku.SudokuResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SudokuResponse::IsInitialized() const {
  return true;
}

void SudokuResponse::Swap(SudokuResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SudokuResponse::InternalSwap(SudokuResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  checkerboard_.Swap(&other->checkerboard_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(solved_, other->solved_);
}

::google::protobuf::Metadata SudokuResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_sudoku_2eproto);
  return ::file_level_metadata_sudoku_2eproto[kIndexInFileMessages];
}


// ===================================================================

SudokuService::~SudokuService() {}

const ::google::protobuf::ServiceDescriptor* SudokuService::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_sudoku_2eproto);
  return file_level_service_descriptors_sudoku_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* SudokuService::GetDescriptor() {
  return descriptor();
}

void SudokuService::Solve(::google::protobuf::RpcController* controller,
                         const ::sudoku::SudokuRequest*,
                         ::sudoku::SudokuResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Solve() not implemented.");
  done->Run();
}

void SudokuService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_sudoku_2eproto[0]);
  switch(method->index()) {
    case 0:
      Solve(controller,
             ::google::protobuf::down_cast<const ::sudoku::SudokuRequest*>(request),
             ::google::protobuf::down_cast< ::sudoku::SudokuResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& SudokuService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::sudoku::SudokuRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& SudokuService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::sudoku::SudokuResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

SudokuService_Stub::SudokuService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
SudokuService_Stub::SudokuService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
SudokuService_Stub::~SudokuService_Stub() {
  if (owns_channel_) delete channel_;
}

void SudokuService_Stub::Solve(::google::protobuf::RpcController* controller,
                              const ::sudoku::SudokuRequest* request,
                              ::sudoku::SudokuResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sudoku
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::sudoku::SudokuRequest* Arena::CreateMaybeMessage< ::sudoku::SudokuRequest >(Arena* arena) {
  return Arena::CreateInternal< ::sudoku::SudokuRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sudoku::SudokuResponse* Arena::CreateMaybeMessage< ::sudoku::SudokuResponse >(Arena* arena) {
  return Arena::CreateInternal< ::sudoku::SudokuResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
